### ISSUE TITLE
What are useful resources for learning more about blockchains and their use in education?

### ISSUE THREAD

**Issue by hathawayjess** [usedgov/blockchain#2]

**Comment by tkendal** [comment]
I've been curating a basic **[Blockchain Education Resource Wiki](https://github.com/tkendal/Edu-Blockchain-Repo/wiki)**. Feel free to reference an/or contribute.

**Comment by syesko** [comment]
Taylor/Jess - Good morning. Will you be attending ISTE in Philadelphia? I will be there M & T and would like to meet to discuss blockchain/DLT edtech space. Thanks, Steve

**Comment by tkendal** [comment]
Unfortunately, I won’t be at ISTE, but @sharon will be.  For anyone attending, be sure to stop by her session: https://conference.iste.org/2019/program/search/detail_session.php?id=112444499

**Comment by reill110** [comment]
Thank you for sharing the blockchain wiki!

**Comment by tkendal** [comment]
@reill110 Absolutely...feel free to make additional suggestions/contributions.

**Comment by radschools** [comment]
This is great @tkendal !  Didn't know this was here

**Comment by tkendal** [comment]
> This is great @tkendal ! Didn't know this was here

@radschools Yeah, it was a seed planted during my brief time at OET. Hoping to revived it in some form/fashion.
