### ISSUE TITLE
Where can we find good summaries of the principles of SSI?

### ISSUE THREAD

**Issue by sharonleu** [usedgov/blockchain#4]
- [Web of Trust] Principles of SSI: https://github.com/WebOfTrustInfo/self-sovereign-identity/blob/master/self-sovereign-identity-principles.md
- [Evernym] An Introduction to Self Sovereign Identity: https://www.youtube.com/watch?v=HMrBP55xROc&app=desktop

**Comment by nsmolenski** [comment]
Multi-Author, [A Comprehensive Guide to Self-Sovereign Identity](https://www.amazon.com/Comprehensive-Guide-Self-Sovereign-Identity-ebook/dp/B07Q3TXLDP/ref=sr_1_3?crid=2J3JV3KGB5IPO&keywords=self-sovereign+identity&qid=1576760457&sprefix=self-sovereign+identity%2Caps%2C181&sr=8-3)

[The European Union Blockchain Observatory and Forum, "Blockchain and Digital Identity"](https://www.eublockchainforum.eu/sites/default/files/report_identity_v0.9.4.pdf)

Kaliya Young, "[There’s A Facebook Alternative, It’s Called Self-Sovereign Identity](https://www.coindesk.com/theres-alternative-facebook-called-self-sovereign-identity)."

Natalie Smolenski, "[Identity and Digital Self-Sovereignty: A New Paradigm for Sovereignty on the High Seas](https://medium.com/learning-machine-blog/identity-and-digital-self-sovereignty-1f3faab7d9e3)."

**Comment by Custard7** [comment]
Great suggestions @nsmolenski & @sharonleu! I'll throw a few more into the discussion:

Kim Cameron, [The Laws of Identity](https://www.identityblog.com/stories/2005/05/13/TheLawsOfIdentity.pdf) - very thoughtful space for understanding the underlying principles and evolution of SSI (and why Microsoft failed at it)

Mariana Dahan [How Proof of Who You Are Can Change the Life You Lead ](https://www.youtube.com/watch?v=wylCxMUH6VE&feature=youtu.be) - Leads the World Identity Network using Identity to achieve the SDGs. Very passionate and intelligent speaker able to distill the significance of SSI. 

Jacksón Smith, [Convivial Identity: Digital Palaces for the People](https://www.diplomaticourier.com/posts/convivial-identity-digital-palaces-for-the-people) - wrote this as a survey of SSI discourse, synthesizing the key challenges: confusing design, fragmented technology, and abusive politics. References the above two pieces!
